### ISSUE TITLE
fix error when running examples.py on macOS in docker 

### ISSUE THREAD

**Issue by fritzphilipp** [assume-framework/assume#151]
ERROR:assume.world:could not connect to postgresql://assume:assume@localhost:5432/assume, trying again

Docker compose logs see attached files (in second file we commented out line 12&13 in compose.yml and put image:postgres)
[Docker_Logs_1.pdf](https://github.com/assume-framework/assume/files/12376501/Docker_Logs_1.pdf)
[Docker_Logs_2.pdf](https://github.com/assume-framework/assume/files/12376502/Docker_Logs_2.pdf)

**Comment by maurerle** [comment]
Hi @fritzphilipp,

first of all thanks for the logs.
In the future, better send the logs to a pastebin service or  but a pdf log file is innovative too ;)
I can confirm that timescaledb indeed has multiple prints of these hello messages.

In the first log file, you can see that some queries issued by Grafana when we tested it, failed, because no data is available yet.
So the database is reachable and works basically..

Then there is the question why local port 5432 is not reachable.
I pushed some better reporting to main in #150 - so you should look at the reported error from that.
Please tell me what the error message says on current main.

I suspect something firewall related..
If something else would already be running on port 5432, docker should have reported that earlier..

**Comment by nick-harder** [comment]
I have mac and for me all the examples work fine. Maybe this is your antivirus software?

**Comment by fritzphilipp** [comment]
Hi @maurerle thanks for your answer! My error when running examples.py on current main is the following:

> ERROR:assume.world:could not connect to postgresql://assume:assume@localhost:5432/assume, trying again
> ERROR:assume.world:(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  role "assume" does not exist
(Background on this error at: https://sqlalche.me/e/20/e3q8).

Maybe you can help me better with that?

**Comment by nick-harder** [comment]
This is because the docker is not running for you. try installing it and running

**Comment by fritzphilipp** [comment]
Docker is running on the right ports but it doesn't work either.

**Comment by maurerle** [comment]
So somehow your container did not create the user `assume` on your database "server".

This is normally done in the `compose.yml` with:

```
    environment:
      - POSTGRES_USER=assume
```

So you have:
* up-to-date docker
* up-to-date macOS
* have run `docker-compose down && rm -r docker-db && docker-compose up -d`

The issue is probably, that postgresql does not have permission to create files in your current folder, therefore not creating the assume user.
You can verify that this is the problem by removing 

```
    volumes:
      - ./assume-db:/var/lib/postgresql
```

from the compose.yml and trying again.

If this is indeed the case, you might need to fix your folder permissions in the `assume-db` folder.
But changing to 

```
volumes:
  - ./assume-db:/var/lib/postgresql/data
```
with /data at the end might help too.

**Comment by maurerle** [comment]
The error was that postgresql was installed with brew (as well as postgis and spatialite-gui).
I wonder why this did not produce issues earlier like "port already in use" - but this seems to be some macos brew magic.

So he was always connecting to the local postgresql instead of to the docker container.
We fixed this by uninstalling postgresql.

If parallel postgresql installation is needed, one could change the local postgresql port in the compose.yml
