### ISSUE TITLE
When CRM and EOM is used, the market_dispatch is not saved for every clearing

### ISSUE THREAD

**Issue by adamsjohanna** [assume-framework/assume#290]
Using the example "small_with_crm", the market dispatch is not saved in the output for those hours, when CRM and EOM both clear
-> No data points in Grafarna

**Comment by nick-harder** [comment]
@maurerle do you have any idea where we might look for this error?

**Comment by maurerle** [comment]
So the problem you are describing, is that when running
`assume -s example_01c -c eom_and_crm --db-uri postgresql://assume:assume@localhost:5432/assume`
you get this visualization:

![image](https://github.com/assume-framework/assume/assets/25026204/255db02a-7213-4a18-a96a-0eeddb217c6d)

which has missing values for the market_dispatch for all units at every fourth hour, while the actual dispatch is written.

When looking into `write_actual_dispatch`, I found that the `market_dispatch` is often empty when it should not be.
After first suspecting the `aggregate_step_amount` function, I found that relevant times were skipped for each `product_type`.
This is because we did not yet calculate the `last_sent_dispatch` per product_type.

With this change we also see the dispatch to the CRM markets, though it seems that there is something wrong:

![image](https://github.com/assume-framework/assume/assets/25026204/f8377b91-3814-4097-b807-4b08b912305d)

And we see that the market dispatch does not have leftouts anymore:

![image](https://github.com/assume-framework/assume/assets/25026204/84a151c8-cb07-433f-9f32-e6ae24eaae79)
