### ISSUE TITLE
Implement learning functionalities

### ISSUE THREAD

**Issue by nick-harder** [assume-framework/assume#3]
Start with the implementation of the learning functions

**Comment by maurerle** [comment]
Relevant progress was made in #130
Kim is currently working on a functioning sampling method including the MATD3.

**Comment by kim-mskw** [comment]
Running version of the learning is in main. Yet, the learning itself, especially the update function does not work. 
I would suggest the following steps for the further process:

- [ ] hack the dashboard plots in there to allow proper investigation of learning #142 
- [ ] debug collect_initial_expercience, either it is not on at allor it is never turned of
- [ ] manage noise in the exploration process
- [ ] double-check policy update
- [ ] fix save and load policies, this definetly does not work yet since the last run of the process (with learning mode off) is terrible
- [ ] tune learning params (maybe readd some of the observation dimension, we deleted some in comparison to felxable)

**Comment by nick-harder** [comment]
@maurerle this one is done as well or?

**Comment by maurerle** [comment]
Only the tests are missing which are also part of #143 - so yes, we can close this.
I am currently doing the rl tests
