### ISSUE TITLE
`Powerplant.set_dispatch_plan()` is broken for multiple markets

### ISSUE THREAD

**Issue by RobbeSneyders** [assume-framework/assume#493]
Hi,

I believe `Powerplant.set_displatch_plan()` incorrectly corrects the dispatch plan based on min / max power for every market separately instead of for all markets together.

Relevant parts of the code:
https://github.com/assume-framework/assume/blob/ef325c07ec30e2d52bcf335b18aa0f2461746298/assume/units/powerplant.py#L202-L214

Which is unnecessarily duplicated from here:
https://github.com/assume-framework/assume/blob/caa46f771c591eb26ccdcfd8a16188eb204a0e5f/assume/units/powerplant.py#L151-L163

### Minimal reproducible example

I created a minimal reproducible example with the following config:
- A Day-Ahead (DA) market
- An Intraday (ID) market
- A demand agent that demands 125 MWh on the DA market
- A demand agent that demands 175 MWh on the ID market
- A powerplant that generates 300 MWh and bids on both the DA and ID market
  - Min power = 200 MW
  - Max power = 300 MW

You can find the code in [this gist](https://gist.github.com/RobbeSneyders/58c3de69fddc619df628b23495b4c1fa).

The demand bids are always higher in price than the supply bids, so logically the result should be that 125 MWh is sold on the DA market, and 175 MWh is sold on the ID market, making 300 in total.

The obtained result however is that 125 MWh is sold on the DA market, the dispatch plan of the powerplant is set to 200 MW (= min power), and only 300 (max power) - 200 (current dispatch) = 100 MWh is sold on the ID market. See the grafana graph with the powerplant dispatch below.

![image](https://github.com/user-attachments/assets/84afc8ee-6023-4219-a92c-ad55ccb644bc)

**Comment by maurerle** [comment]
Hi @RobbeSneyders ,

Your investigation is correct, that the current behavior is not intended.

However, I think that the fix in this case would be to move the ramping checks to a different (later) place instead of in the set_dispatch_plan function.

In `handle_market_feedback` we do 

```python
self.set_unit_dispatch(orderbook, marketconfig)
self.write_actual_dispatch(marketconfig.product_type)
```

The `set_unit_dispatch` function adds the accepted orders from the market to our actual dispatch.
The `write_actual_dispatch` writes all the bids which are considered as "in the past" to the output and should calculate the ramping constraints and min power.


```mermaid
gantt
    title Market Schedule ID + DAM
      dateFormat  YYY-MM-DD HH:mm
      axisFormat %H:%M
      section First
      Bidding EOM          :a1, 2019-01-01 12:00, 30m
      Delivery01 EOM         :2019-01-01 13:00, 1h
      Delivery02 EOM         :2019-01-01 14:00, 1h
      section Second
      Bidding1 ID          :a1, 2019-01-01 12:30, 30m
      Delivery1 ID         :2019-01-01 13:00, 30m
      Bidding2 ID          :a1, 2019-01-01 13:00, 30m
      Delivery2 ID         :2019-01-01 13:30, 30m
      Bidding3 ID          :a1, 2019-01-01 13:30, 30m
      Delivery3 ID         :2019-01-01 14:00, 30m
```

So at 12:30 the `set_unit_dispatch` function is executed, and at the retrieval of the next market results which is at or after the start time of the bids to accept (13:00) we will write the actual result (and turn our powerplant off if needed)

If we have only a single market like this (the 24 single EOM hour bids are aggregated in the graphic):

```mermaid
gantt
    title Market Schedule ID + DAM
      dateFormat  YYY-MM-DD HH:mm
      axisFormat %H:%M
      section First
      Bidding01 EOM          :a1, 2019-01-01 12:00, 30m
      Delivery01 EOM         :2019-01-01 13:00, 24h
      Bidding02 EOM          :a1, 2019-01-02 12:00, 30m
      Delivery02 EOM         :2019-01-02 13:00, 24h
```

and the last bid (2019-01-02 12:00-13:00) of the EOM market did not win enough, so we have to ramp down  (which we already know at 2019-01-01 12:30)
but we do not apply turning off our power plant until the end of the first market period at or after the start time of our delivery (delivery is 2019-01-02 12:00) - so we would apply the ramping at 2019-01-02 12:30, which is bad, as we did bid in the second period under the assumption of having a powerplant which is turned on - but we actually have to turn it off due to ramping constraints.

I mean, in reality, we would leave our powerplant on, but you can imagine cases in which this is not the case.

So
1. applying the ramping constraints should be moved to `write_actual_dispatch` instead of `set_unit_dispatch` as other markets can add to the dispatch
2. The function `write_actual_dispatch` has to be executed regularly and writes the values for all timestamps which are considered in the past, but it does not have hard requirements when to run
3. if we `write_actual_dispatch` to early, we did apply ramping/shut down our powerplant even though we could have used it further, if we apply ramping/shut down to late, and bid with wrong assumptions about the next bidding period.

So this is still an open issue I think. Thank you for reporting!

**Comment by maurerle** [comment]
So ramping is already respected in `execute_current_dispatch` and we never shut down a power plant if it does not reach the min power

```python
if current_power > 0:
        current_power = min(current_power, max_power[t])
        current_power = max(current_power, self.min_power)
```

So my remarks are currently not the case, and your PR looks fine for me :)
